import "./globals.css";
import Navbar from "@/components/Navigation";
import Footer from "@/components/Footer";

export const metadata = {
  title: "API Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html className="scroll-smooth" lang="en">
      <body>
      {/*<Navbar/>*/}
      {children}
      <Footer/>
      </body>
      </html>
  );
}
